### ISSUE TITLE
Integrate Casbin into Istio

### ISSUE THREAD

**Issue by hsluoyz** [casbin/envoy-authz#1]
This will be similar to:

1. https://github.com/open-policy-agent/opa-envoy-plugin
2. https://github.com/tsandall/minimal-opa-envoy-example
3. https://github.com/open-policy-agent/opa-envoy-spire-ext-authz

**Comment by hsluoyz** [comment]
@ashish493 created here: https://github.com/casbin/envoy-authz

**Comment by hsluoyz** [comment]
@ComradeProgrammer plz test this envoy-authz middleware based on the official guide: https://istio.io/latest/docs/tasks/security/authorization/authz-custom/

**Comment by ashish493** [comment]
@hsluoyz , I have only added the deployment file and Dockerfile for server. I still need to create the grpc server(for authorizing all queries through casbin) which is under construction.

**Comment by ComradeProgrammer** [comment]
So do I still need to test this middleware, or shall I wait for the implementation of grpc server?
@hsluoyz

**Comment by hsluoyz** [comment]
OK. @ashish493 @ComradeProgrammer plz note that our final goal would be becoming a 3rd-party authorization solution for Istio like: https://istio.io/latest/blog/2021/better-external-authz/

![image](https://user-images.githubusercontent.com/3787410/126890110-25a73fae-b416-4335-a598-633eeacaca17.png)

**Comment by hsluoyz** [comment]
Done at: https://github.com/casbin/envoy-authz
