### ISSUE TITLE
Add this envoy-authz middleware to the official list

### ISSUE THREAD

**Issue by hsluoyz** [casbin/envoy-authz#3]
We have several options to integrate this repo into the envoy/istio ecosystem, like code integration, listing in the 3rd-party authorization middleware list, etc. See how we did it for apisix middleware: casbin-lua/apisix-authz#5 . `apisix-authz` has already integrated its code into apisix's main trunk. I think this is a very good example.

See: https://istio.io/latest/blog/2021/better-external-authz/

![image](https://user-images.githubusercontent.com/3787410/126890110-25a73fae-b416-4335-a598-633eeacaca17.png)

**Comment by hsluoyz** [comment]
@ashish493

**Comment by ashish493** [comment]
@hsluoyz , I had created an issue here :- https://github.com/istio/istio.io/issues/10171
Still waiting for their reply.

**Comment by hsluoyz** [comment]
Hi @ashish493 , see the reply: https://github.com/istio/istio.io/issues/10171#issuecomment-912004209

**Comment by ashish493** [comment]
Working on it!

**Comment by ashish493** [comment]
@hsluoyz , the PR of adding the plugin is merged :- https://github.com/istio/istio.io/pull/10302
Just waiting for it to get released on the website. For now, u can check here:- https://deploy-preview-10302--preliminary-istio.netlify.app/latest/about/ecosystem under the section of integrations.

Now here: https://istio.io/latest/about/ecosystem/

**Comment by hsluoyz** [comment]
@ashish493 great, thanks!

![image](https://user-images.githubusercontent.com/3787410/132370802-62fcbd36-0225-43e8-b670-c2cdc8a7dae5.png)
